"""CPU-friendly learned dynamics over the complete symbolic game state.

The neural Q policy deliberately keeps a compact 42-feature input. The learned
model receives both that policy state and a lossless symbolic representation
of the observable game state. During planning it predicts a complete next
game state, which can be converted back into the compact policy features.
"""

from dataclasses import dataclass, replace
import random

import numpy as np
from sklearn.neural_network import MLPClassifier, MLPRegressor

import settings as s


N_ACTIONS = 6
N_STATE_FEATURES = 42
REWARD_SCALE = 20.0
OPPONENT_ACTIONS = ("UP", "RIGHT", "DOWN", "LEFT", "WAIT", "BOMB", "REMOVED")
OPPONENT_REMOVED_INDEX = 6
OPPONENT_ACTION_DELTAS = (
    (0, -1),
    (1, 0),
    (0, 1),
    (-1, 0),
    (0, 0),
    (0, 0),
)

FIELD_CHANNEL = 0
COIN_CHANNEL = 1
BOMB_CHANNEL = 2
EXPLOSION_CHANNEL = 3
SELF_CHANNEL = 4
OTHER_CHANNEL = 5
OTHER_BOMB_CHANNEL = 6
N_BOARD_CHANNELS = 7
N_WORLD_SCALARS = 5

# A plain mean-squared loss would be dominated by thousands of unchanged board
# cells. Scaling targets implements component weighting without increasing the
# network size: dynamic entities, reward, termination and legality receive a
# much larger gradient than static background cells.
CHANNEL_TARGET_WEIGHTS = np.asarray(
    (1.0, 2.0, 6.0, 6.0, 12.0, 8.0, 8.0),
    dtype=np.float32,
)
SCALAR_TARGET_WEIGHT = 10.0
AGENT_REWARD_WEIGHT = 3.0
# The current action plus four future environment transitions. This includes
# the BOMB action whose timer expires four ticks after placement.
SUICIDE_RISK_HORIZON = 5
# The factored head already receives up to 96 opponent samples per update.
# Training it every transition repeatedly decodes thousands of board cells and
# dominates CPU time without adding independent data.
OPPONENT_TRAIN_EVERY = 16

REPLAY_NORMAL = "normal"
REPLAY_BOMB = "bomb"
REPLAY_DANGER = "danger"
REPLAY_TERMINAL = "terminal"
REPLAY_CATEGORIES = (
    REPLAY_NORMAL,
    REPLAY_BOMB,
    REPLAY_DANGER,
    REPLAY_TERMINAL,
)
REPLAY_CATEGORY_RATIOS = {
    REPLAY_NORMAL: 0.40,
    REPLAY_BOMB: 0.20,
    REPLAY_DANGER: 0.25,
    REPLAY_TERMINAL: 0.15,
}

BOMB_DOMAIN = (-1, 0, 1, 2, 3, 4)
BOMB_NORMALIZED = np.linspace(-1.0, 1.0, len(BOMB_DOMAIN))
EXPLOSION_DOMAIN = tuple(range(s.EXPLOSION_TIMER + 1))
EXPLOSION_NORMALIZED = np.linspace(
    -1.0,
    1.0,
    len(EXPLOSION_DOMAIN),
)
MAX_COIN_COUNT = 50
MAX_BOMB_COUNT = s.MAX_AGENTS
MAX_OTHER_COUNT = s.MAX_AGENTS - 1

# Compact policy features are auxiliary inputs. The world model itself
# predicts the much richer state defined by the board channels above.
STATE_DOMAINS = (
    ((0, 1),) * 4
    + ((-1, 0, 1),) * 4
    + ((0, 1),) * 4
    + ((0, 1, 2, 3, 4),)
    + ((0, 1, 2, 3),)
    + ((0, 1),) * 12
    + ((0, 1),) * 4
    + ((0, 1, 2, 3, 4),)
    + ((0, 1),) * 4
    + ((0, 1),) * 4
    + ((0, 1, 2, 3, 4),)
    + ((0, 1),)
    + ((0, 1, 2, 3, 4),)
)

if len(STATE_DOMAINS) != N_STATE_FEATURES:
    raise RuntimeError("The policy-state domains do not match its state size.")


def _normalized_domain(domain):
    if len(domain) == 1:
        return np.zeros(1, dtype=np.float32)
    return np.linspace(-1.0, 1.0, len(domain), dtype=np.float32)


NORMALIZED_DOMAINS = tuple(
    _normalized_domain(domain)
    for domain in STATE_DOMAINS
)


@dataclass(frozen=True)
class WorldState:
    """Canonical vector representation of one observable game state."""

    shape: tuple
    round_number: int
    vector: tuple


@dataclass(frozen=True)
class Experience:
    """One real transition used for supervised dynamics learning."""

    state: tuple
    world_state: WorldState
    action_index: int
    reward: float
    next_state: tuple | None
    next_world_state: WorldState | None
    done: bool
    valid_actions: tuple
    next_valid_actions: tuple
    replay_category: str = REPLAY_NORMAL
    death_within_horizon: bool | None = None
    suicide_within_horizon: bool | None = None


@dataclass(frozen=True)
class Prediction:
    """A complete transition generated by the learned world model."""

    reward: float
    next_world_state: WorldState
    next_state: tuple
    done_probability: float
    next_valid_actions: tuple
    death_probability: float = 0.0
    suicide_probability: float = 0.0


@dataclass(frozen=True)
class BombOutcome:
    """Observed delayed outcome of one accepted BOMB action."""

    state: tuple
    survived: bool
    destroyed_crate: bool
    killed_opponent: bool
    opponent_escaped: bool


@dataclass(frozen=True)
class BombOutcomePrediction:
    survived_probability: float
    crate_probability: float
    kill_probability: float
    escape_probability: float


def encode_state(state):
    """Normalize a compact discrete policy state."""

    if len(state) != N_STATE_FEATURES:
        raise ValueError(
            f"Expected {N_STATE_FEATURES} policy features, got {len(state)}."
        )

    encoded = np.empty(N_STATE_FEATURES, dtype=np.float32)
    for index, (value, domain, normalized) in enumerate(
        zip(state, STATE_DOMAINS, NORMALIZED_DOMAINS)
    ):
        try:
            category = domain.index(int(value))
        except ValueError as error:
            raise ValueError(
                f"Feature {index} has invalid value {value}; domain={domain}."
            ) from error
        encoded[index] = normalized[category]
    return encoded


def decode_state(encoded):
    """Project a continuous policy-state prediction onto valid categories."""

    values = []
    for prediction, domain, normalized in zip(
        encoded,
        STATE_DOMAINS,
        NORMALIZED_DOMAINS,
    ):
        category = int(np.argmin(np.abs(normalized - prediction)))
        values.append(domain[category])
    return tuple(values)


def _channel_slices(shape):
    board_size = int(np.prod(shape))
    return tuple(
        slice(channel * board_size, (channel + 1) * board_size)
        for channel in range(N_BOARD_CHANNELS)
    )


def world_vector_size(shape):
    return N_BOARD_CHANNELS * int(np.prod(shape)) + N_WORLD_SCALARS


def world_target_weights(shape):
    """Return per-output weights for one flattened world-state vector."""

    board_size = int(np.prod(shape))
    return np.concatenate(
        (
            np.repeat(CHANNEL_TARGET_WEIGHTS, board_size),
            np.full(
                N_WORLD_SCALARS,
                SCALAR_TARGET_WEIGHT,
                dtype=np.float32,
            ),
        )
    )


def _count_to_normalized(count, maximum):
    return 2.0 * np.clip(float(count) / maximum, 0.0, 1.0) - 1.0


def _normalized_to_count(value, maximum):
    return int(
        np.clip(
            np.rint((float(value) + 1.0) * 0.5 * maximum),
            0,
            maximum,
        )
    )


def _categorical_to_normalized(value, domain, normalized):
    value = int(value)
    if value not in domain:
        value = min(domain, key=lambda item: abs(item - value))
    return float(normalized[domain.index(value)])


def _normalized_to_categorical(value, domain, normalized):
    return domain[int(np.argmin(np.abs(normalized - value)))]


def game_state_to_world_state(game_state):
    """Encode the complete observable game state into symbolic channels."""

    if game_state is None:
        return None

    field = np.asarray(game_state["field"], dtype=np.float32)
    shape = tuple(int(value) for value in field.shape)
    board_size = int(np.prod(shape))
    channels = np.full(
        (N_BOARD_CHANNELS, board_size),
        -1.0,
        dtype=np.float32,
    )

    channels[FIELD_CHANNEL] = field.reshape(-1)

    coin_mask = np.zeros(shape, dtype=bool)
    for position in game_state["coins"]:
        coin_mask[position] = True
    channels[COIN_CHANNEL] = np.where(
        coin_mask.reshape(-1),
        1.0,
        -1.0,
    )

    bomb_grid = np.full(shape, -1.0, dtype=np.float32)
    for position, timer in game_state["bombs"]:
        bomb_grid[position] = _categorical_to_normalized(
            timer,
            BOMB_DOMAIN,
            BOMB_NORMALIZED,
        )
    channels[BOMB_CHANNEL] = bomb_grid.reshape(-1)

    explosion_map = np.asarray(
        game_state.get("explosion_map", np.zeros(shape)),
        dtype=np.int16,
    )
    explosion_grid = np.empty(shape, dtype=np.float32)
    for value in EXPLOSION_DOMAIN:
        explosion_grid[explosion_map == value] = (
            EXPLOSION_NORMALIZED[value]
        )
    explosion_grid[explosion_map > EXPLOSION_DOMAIN[-1]] = 1.0
    channels[EXPLOSION_CHANNEL] = explosion_grid.reshape(-1)

    self_mask = np.full(shape, -1.0, dtype=np.float32)
    self_mask[game_state["self"][3]] = 1.0
    channels[SELF_CHANNEL] = self_mask.reshape(-1)

    other_mask = np.full(shape, -1.0, dtype=np.float32)
    other_bomb_grid = np.full(shape, -1.0, dtype=np.float32)
    for other in game_state["others"]:
        position = other[3]
        other_mask[position] = 1.0
        other_bomb_grid[position] = 1.0 if bool(other[2]) else 0.0
    channels[OTHER_CHANNEL] = other_mask.reshape(-1)
    channels[OTHER_BOMB_CHANNEL] = other_bomb_grid.reshape(-1)

    scalars = np.asarray(
        [
            1.0 if bool(game_state["self"][2]) else -1.0,
            _count_to_normalized(
                game_state.get("step", 1),
                s.MAX_STEPS,
            ),
            _count_to_normalized(
                len(game_state["coins"]),
                MAX_COIN_COUNT,
            ),
            _count_to_normalized(
                len(game_state["bombs"]),
                MAX_BOMB_COUNT,
            ),
            _count_to_normalized(
                len(game_state["others"]),
                MAX_OTHER_COUNT,
            ),
        ],
        dtype=np.float32,
    )
    vector = np.concatenate((channels.reshape(-1), scalars))
    return WorldState(
        shape=shape,
        round_number=int(game_state.get("round", 0)),
        vector=tuple(float(value) for value in vector),
    )


def _top_positions(scores, count, valid_mask=None):
    scores = np.asarray(scores, dtype=np.float32).copy()
    if valid_mask is not None:
        scores[~np.asarray(valid_mask, dtype=bool)] = -np.inf
    finite_count = int(np.sum(np.isfinite(scores)))
    count = min(int(count), finite_count)
    if count <= 0:
        return []
    indices = np.argpartition(scores, -count)[-count:]
    return [int(index) for index in indices]


def world_state_to_game_state(world_state):
    """Decode and project a vector into a mechanically valid game state."""

    shape = tuple(world_state.shape)
    board_size = int(np.prod(shape))
    vector = np.asarray(world_state.vector, dtype=np.float32)
    if len(vector) != world_vector_size(shape):
        raise ValueError("World-state vector has an incompatible size.")

    slices = _channel_slices(shape)
    channels = [vector[channel_slice] for channel_slice in slices]
    scalar_offset = N_BOARD_CHANNELS * board_size
    scalars = vector[scalar_offset:]

    field_values = np.asarray((-1, 0, 1), dtype=np.int8)
    field = field_values[
        np.argmin(
            np.abs(channels[FIELD_CHANNEL][:, None] - field_values[None, :]),
            axis=1,
        )
    ].reshape(shape)

    # Bomberman arenas always have an indestructible outer wall. Enforcing it
    # keeps generated agent positions away from array boundaries.
    field[0, :] = -1
    field[-1, :] = -1
    field[:, 0] = -1
    field[:, -1] = -1

    free_before_self = field.reshape(-1) == 0
    self_scores = channels[SELF_CHANNEL].copy()
    self_scores[~free_before_self] = -np.inf
    self_index = int(np.argmax(self_scores))
    self_position = tuple(
        int(value)
        for value in np.unravel_index(self_index, shape)
    )
    field[self_position] = 0

    free_mask = field.reshape(-1) == 0
    other_count = _normalized_to_count(scalars[4], MAX_OTHER_COUNT)
    other_candidates = free_mask.copy()
    other_candidates[self_index] = False
    other_indices = _top_positions(
        channels[OTHER_CHANNEL],
        other_count,
        valid_mask=other_candidates,
    )
    others = []
    for number, index in enumerate(other_indices):
        position = tuple(
            int(value)
            for value in np.unravel_index(index, shape)
        )
        bombs_left = channels[OTHER_BOMB_CHANNEL][index] >= 0.5
        others.append(
            (f"predicted_opponent_{number}", 0, bombs_left, position)
        )

    coin_candidates = free_mask.copy()
    coin_candidates[self_index] = False
    if other_indices:
        coin_candidates[other_indices] = False
    coin_count = _normalized_to_count(scalars[2], MAX_COIN_COUNT)
    coin_indices = _top_positions(
        channels[COIN_CHANNEL],
        coin_count,
        valid_mask=coin_candidates,
    )
    coins = [
        tuple(int(value) for value in np.unravel_index(index, shape))
        for index in coin_indices
    ]

    bomb_count = _normalized_to_count(scalars[3], MAX_BOMB_COUNT)
    bomb_indices = _top_positions(
        channels[BOMB_CHANNEL],
        bomb_count,
        valid_mask=free_mask,
    )
    bombs = []
    for index in bomb_indices:
        position = tuple(
            int(value)
            for value in np.unravel_index(index, shape)
        )
        timer = _normalized_to_categorical(
            channels[BOMB_CHANNEL][index],
            BOMB_DOMAIN[1:],
            BOMB_NORMALIZED[1:],
        )
        bombs.append((position, int(timer)))

    explosion_flat = np.asarray(
        [
            _normalized_to_categorical(
                value,
                EXPLOSION_DOMAIN,
                EXPLOSION_NORMALIZED,
            )
            for value in channels[EXPLOSION_CHANNEL]
        ],
        dtype=np.int8,
    )
    explosion_map = explosion_flat.reshape(shape)

    step = max(
        1,
        _normalized_to_count(scalars[1], s.MAX_STEPS),
    )
    return {
        "round": int(world_state.round_number),
        "step": step,
        "field": field,
        "self": (
            "predicted_self",
            0,
            bool(scalars[0] >= 0.0),
            self_position,
        ),
        "others": others,
        "bombs": bombs,
        "coins": coins,
        "explosion_map": explosion_map,
        "user_input": None,
    }


def project_world_state(world_state):
    """Return a canonical state after enforcing discrete game invariants."""

    return game_state_to_world_state(
        world_state_to_game_state(world_state)
    )


def actions_to_mask(actions):
    mask = np.full(N_ACTIONS, -1.0, dtype=np.float32)
    for action_index in actions:
        mask[int(action_index)] = 1.0
    return mask


class LearnedWorldModel:
    """Incremental residual model of the complete observable game state."""

    def __init__(
        self,
        replay_capacity=20_000,
        batch_size=32,
        min_samples=256,
        hidden_size=32,
        learning_rate=0.001,
        seed=7,
        suicide_risk_horizon=SUICIDE_RISK_HORIZON,
        risk_replay_capacity=5_000,
        bomb_outcome_capacity=5_000,
    ):
        self.replay_capacity = int(replay_capacity)
        self.batch_size = int(batch_size)
        self.min_samples = int(min_samples)
        self.seed = int(seed)
        self.suicide_risk_horizon = int(suicide_risk_horizon)
        self.risk_replay_capacity = int(risk_replay_capacity)
        self.replay = []
        self.replay_position = 0
        self.category_indices = {
            category: set()
            for category in REPLAY_CATEGORIES
        }
        self.pending_risk_indices = []
        # Only compact (state, action) pairs are retained here. Keeping the
        # 2,000-value board vectors again would make checkpoints unnecessarily
        # large. These positive examples survive main replay-buffer rollover.
        self.death_risk_replay = []
        self.suicide_risk_replay = []
        self.bomb_outcome_capacity = int(bomb_outcome_capacity)
        self.bomb_outcome_replay = []
        self.bomb_rare_capacity = 1_000
        self.bomb_kill_replay = []
        self.bomb_failure_replay = []
        self.pending_bomb_outcome = None
        self.bomb_outcomes_trained = 0
        self.last_batch_category_counts = None
        self.total_observations = 0
        self.training_steps = 0
        self.last_loss = None
        self.board_shape = None
        self.rng = random.Random(seed)
        self.dynamics_model = MLPRegressor(
            hidden_layer_sizes=(hidden_size, hidden_size),
            activation="tanh",
            solver="adam",
            learning_rate_init=learning_rate,
            max_iter=1,
            warm_start=True,
            random_state=seed,
        )
        self.agent_model = MLPRegressor(
            hidden_layer_sizes=(64, 64),
            activation="tanh",
            solver="adam",
            learning_rate_init=learning_rate,
            max_iter=1,
            warm_start=True,
            random_state=seed + 1,
        )
        self.done_model = MLPClassifier(
            hidden_layer_sizes=(32,),
            activation="tanh",
            solver="adam",
            learning_rate_init=learning_rate,
            max_iter=1,
            random_state=seed + 2,
        )
        self.death_model = MLPClassifier(
            hidden_layer_sizes=(32,),
            activation="tanh",
            solver="adam",
            learning_rate_init=learning_rate,
            max_iter=1,
            random_state=seed + 3,
        )
        self.suicide_model = MLPClassifier(
            hidden_layer_sizes=(32,),
            activation="tanh",
            solver="adam",
            learning_rate_init=learning_rate,
            max_iter=1,
            random_state=seed + 4,
        )
        self._create_bomb_outcome_models(hidden_size, learning_rate)
        self._create_opponent_model(hidden_size, learning_rate)

    def _create_bomb_outcome_models(self, hidden_size=32, learning_rate=0.001):
        def classifier(seed_offset):
            return MLPClassifier(
                hidden_layer_sizes=(hidden_size,),
                activation="tanh",
                solver="adam",
                learning_rate_init=learning_rate,
                max_iter=1,
                random_state=self.seed + seed_offset,
            )

        self.bomb_survival_model = classifier(5)
        self.bomb_crate_model = classifier(6)
        self.bomb_kill_model = classifier(7)
        self.bomb_escape_model = classifier(8)

    def _create_opponent_model(self, hidden_size=32, learning_rate=0.001):
        self.opponent_model = MLPClassifier(
            hidden_layer_sizes=(hidden_size, hidden_size),
            activation="tanh",
            solver="adam",
            learning_rate_init=learning_rate,
            max_iter=1,
            random_state=self.seed + 9,
        )
        self.opponent_training_steps = 0
        self.opponent_last_loss = None

    def ensure_bomb_outcome_state(self):
        """Upgrade a V16 checkpoint created before bomb outcomes existed."""

        if not hasattr(self, "bomb_outcome_capacity"):
            self.bomb_outcome_capacity = 5_000
        if not hasattr(self, "bomb_outcome_replay"):
            self.bomb_outcome_replay = []
        if not hasattr(self, "bomb_rare_capacity"):
            self.bomb_rare_capacity = 1_000
        if not hasattr(self, "bomb_kill_replay"):
            self.bomb_kill_replay = [
                item
                for item in self.bomb_outcome_replay
                if item.killed_opponent
            ][-self.bomb_rare_capacity:]
        if not hasattr(self, "bomb_failure_replay"):
            self.bomb_failure_replay = [
                item
                for item in self.bomb_outcome_replay
                if not item.survived
            ][-self.bomb_rare_capacity:]
        if not hasattr(self, "pending_bomb_outcome"):
            self.pending_bomb_outcome = None
        if not hasattr(self, "bomb_outcomes_trained"):
            self.bomb_outcomes_trained = 0
        if not hasattr(self, "bomb_survival_model"):
            self._create_bomb_outcome_models()

    def ensure_opponent_model_state(self):
        """Upgrade checkpoints created before factored opponent dynamics."""

        if not hasattr(self, "opponent_model"):
            self._create_opponent_model()
        if not hasattr(self, "opponent_training_steps"):
            self.opponent_training_steps = 0
        if not hasattr(self, "opponent_last_loss"):
            self.opponent_last_loss = None

    @property
    def is_ready(self):
        return (
            len(self.replay) >= self.min_samples
            and hasattr(self.dynamics_model, "coefs_")
            and hasattr(self.agent_model, "coefs_")
            and hasattr(self.done_model, "classes_")
        )

    def __len__(self):
        return len(self.replay)

    @property
    def is_suicide_model_ready(self):
        return hasattr(self.suicide_model, "classes_")

    @property
    def is_death_model_ready(self):
        return hasattr(self.death_model, "classes_")

    @property
    def is_bomb_outcome_ready(self):
        return (
            len(self.bomb_outcome_replay) >= 32
            and all(
                hasattr(model, "classes_")
                for model in (
                    self.bomb_survival_model,
                    self.bomb_crate_model,
                    self.bomb_kill_model,
                )
            )
        )

    @property
    def is_opponent_model_ready(self):
        return hasattr(self.opponent_model, "classes_")

    def observe_bomb_events(
        self,
        state,
        bomb_dropped=False,
        crate_destroyed=False,
        killed_opponent=False,
        death=False,
        exploded=False,
        done=False,
    ):
        """Accumulate delayed events belonging to the currently owned bomb."""

        self.ensure_bomb_outcome_state()
        if bomb_dropped:
            self.pending_bomb_outcome = {
                "state": tuple(state),
                "destroyed_crate": False,
                "killed_opponent": False,
                "death": False,
            }

        pending = self.pending_bomb_outcome
        if pending is None:
            return
        pending["destroyed_crate"] |= bool(crate_destroyed)
        pending["killed_opponent"] |= bool(killed_opponent)
        pending["death"] |= bool(death)

        if not (exploded or done):
            return

        threatened_opponent = any(pending["state"][35:39])
        outcome = BombOutcome(
            state=pending["state"],
            survived=not pending["death"],
            destroyed_crate=pending["destroyed_crate"],
            killed_opponent=pending["killed_opponent"],
            opponent_escaped=(
                threatened_opponent and not pending["killed_opponent"]
            ),
        )
        self.bomb_outcome_replay.append(outcome)
        if len(self.bomb_outcome_replay) > self.bomb_outcome_capacity:
            del self.bomb_outcome_replay[0]
        if outcome.killed_opponent:
            self.bomb_kill_replay.append(outcome)
            if len(self.bomb_kill_replay) > self.bomb_rare_capacity:
                del self.bomb_kill_replay[0]
        if not outcome.survived:
            self.bomb_failure_replay.append(outcome)
            if len(self.bomb_failure_replay) > self.bomb_rare_capacity:
                del self.bomb_failure_replay[0]
        self.pending_bomb_outcome = None

    def _append_risk_example(self, replay, experience):
        replay.append((experience.state, experience.action_index))
        if len(replay) > self.risk_replay_capacity:
            del replay[0]

    def _set_risk_targets(self, replay_index, death, suicide):
        experience = self.replay[replay_index]
        labeled = replace(
            experience,
            death_within_horizon=bool(death),
            suicide_within_horizon=bool(suicide),
        )
        self.replay[replay_index] = labeled
        if death:
            self._append_risk_example(self.death_risk_replay, labeled)
        if suicide:
            self._append_risk_example(self.suicide_risk_replay, labeled)

    def _finish_risk_labels(self, replay_index, done, death, suicide):
        """Label transitions only after their risk horizon is known."""

        self.pending_risk_indices.append(replay_index)
        if len(self.pending_risk_indices) > self.suicide_risk_horizon:
            safe_index = self.pending_risk_indices.pop(0)
            self._set_risk_targets(safe_index, False, False)

        if done:
            for pending_index in self.pending_risk_indices:
                self._set_risk_targets(
                    pending_index,
                    death,
                    suicide,
                )
            self.pending_risk_indices.clear()

    def observe(
        self,
        state,
        world_state,
        action_index,
        reward,
        next_state,
        next_world_state,
        done,
        valid_actions,
        next_valid_actions,
        replay_category=REPLAY_NORMAL,
        death=False,
        suicide=False,
    ):
        """Store one real compact-state/full-state transition."""

        if self.board_shape is None:
            self.board_shape = tuple(world_state.shape)
        if tuple(world_state.shape) != self.board_shape:
            raise ValueError("All world-model states must use one board shape.")
        if replay_category not in REPLAY_CATEGORIES:
            raise ValueError(f"Unknown replay category: {replay_category}.")

        experience = Experience(
            state=tuple(state),
            world_state=world_state,
            action_index=int(action_index),
            reward=float(reward),
            next_state=(tuple(next_state) if next_state is not None else None),
            next_world_state=next_world_state,
            done=bool(done),
            valid_actions=tuple(int(action) for action in valid_actions),
            next_valid_actions=tuple(
                int(action)
                for action in next_valid_actions
            ),
            replay_category=replay_category,
        )

        if len(self.replay) < self.replay_capacity:
            replay_index = len(self.replay)
            self.replay.append(experience)
        else:
            replay_index = self.replay_position
            old_category = self.replay[replay_index].replay_category
            self.category_indices[old_category].discard(replay_index)
            self.pending_risk_indices = [
                index
                for index in self.pending_risk_indices
                if index != replay_index
            ]
            self.replay[self.replay_position] = experience
        self.category_indices[replay_category].add(replay_index)
        self.replay_position = (
            self.replay_position + 1
        ) % self.replay_capacity
        self.total_observations += 1
        self._finish_risk_labels(
            replay_index,
            bool(done),
            bool(death),
            bool(suicide),
        )

    def sample_start(self, rng):
        return self.replay[rng.randrange(len(self.replay))]

    def _balanced_batch(self, sample_size):
        """Sample all important transition types, with replacement."""

        desired = {
            category: int(sample_size * ratio)
            for category, ratio in REPLAY_CATEGORY_RATIOS.items()
        }
        assigned = sum(desired.values())
        for category in REPLAY_CATEGORIES:
            if assigned >= sample_size:
                break
            desired[category] += 1
            assigned += 1

        batch = []
        actual_counts = {
            category: 0
            for category in REPLAY_CATEGORIES
        }
        missing = 0
        for category in REPLAY_CATEGORIES:
            candidates = tuple(self.category_indices[category])
            if not candidates:
                missing += desired[category]
                continue
            for _ in range(desired[category]):
                batch.append(self.replay[self.rng.choice(candidates)])
                actual_counts[category] += 1

        for _ in range(missing):
            experience = self.replay[self.rng.randrange(len(self.replay))]
            batch.append(experience)
            actual_counts[experience.replay_category] += 1

        self.rng.shuffle(batch)
        self.last_batch_category_counts = actual_counts
        return batch

    @staticmethod
    def _encode_input(world_state, state, action_index):
        action_vector = np.zeros(N_ACTIONS, dtype=np.float32)
        action_vector[int(action_index)] = 1.0
        return np.concatenate(
            (
                np.asarray(world_state.vector, dtype=np.float32),
                encode_state(state),
                action_vector,
            )
        )

    @staticmethod
    def _encode_agent_input(state, action_index):
        action_vector = np.zeros(N_ACTIONS, dtype=np.float32)
        action_vector[int(action_index)] = 1.0
        return np.concatenate((encode_state(state), action_vector))

    @staticmethod
    def _encode_dynamics_target(experience):
        current_world = np.asarray(
            experience.world_state.vector,
            dtype=np.float32,
        )
        target_world = (
            current_world
            if experience.next_world_state is None
            else np.asarray(
                experience.next_world_state.vector,
                dtype=np.float32,
            )
        )
        world_delta = (
            target_world - current_world
        ) * world_target_weights(experience.world_state.shape)
        return world_delta

    @staticmethod
    def _encode_agent_target(experience):
        target_state = (
            experience.state
            if experience.next_state is None
            else experience.next_state
        )
        reward = np.clip(
            experience.reward / REWARD_SCALE,
            -1.0,
            1.0,
        )
        return np.concatenate(
            (
                encode_state(target_state),
                np.asarray(
                    [
                        reward * AGENT_REWARD_WEIGHT,
                    ],
                    dtype=np.float32,
                ),
                actions_to_mask(experience.next_valid_actions),
            )
        )

    def _train_risk_head(
        self,
        model,
        label_attribute,
        persistent_positive_replay,
        batch,
    ):
        """Train one risk head with retained positives and current negatives."""

        labeled = [
            item
            for item in batch
            if getattr(item, label_attribute) is not None
        ]
        encoded_inputs = [
            self._encode_agent_input(item.state, item.action_index)
            for item in labeled
        ]
        targets = [
            int(getattr(item, label_attribute))
            for item in labeled
        ]

        # Eight retained positives in a normal batch of 32 are strong enough
        # to prevent forgetting without forcing every action to look fatal.
        positive_count = min(
            max(1, self.batch_size // 4),
            len(persistent_positive_replay),
        )
        for _ in range(positive_count):
            state, action_index = self.rng.choice(
                persistent_positive_replay
            )
            encoded_inputs.append(
                self._encode_agent_input(state, action_index)
            )
            targets.append(1)

        if not encoded_inputs:
            return None

        model.partial_fit(
            np.stack(encoded_inputs),
            np.asarray(targets, dtype=np.int8),
            classes=np.asarray((0, 1), dtype=np.int8),
        )
        return float(model.loss_)

    @staticmethod
    def _opponent_view_input(game_state, opponent, action_index):
        """Encode the board from one opponent's translation-invariant view."""

        # Delayed import avoids the callbacks -> q_network -> world_model
        # import cycle while reusing the exact policy feature definition.
        from .callbacks import state_to_key

        opponent_position = opponent[3]
        original_self = game_state["self"]
        other_agents = [
            original_self,
            *[
                other
                for other in game_state["others"]
                if other[3] != opponent_position
            ],
        ]
        opponent_game_state = dict(game_state)
        opponent_game_state["self"] = (
            "modeled_opponent",
            0,
            bool(opponent[2]),
            opponent_position,
        )
        opponent_game_state["others"] = other_agents
        state = state_to_key(opponent_game_state)
        action_onehot = np.full(N_ACTIONS, -1.0, dtype=np.float32)
        action_onehot[int(action_index)] = 1.0
        return np.concatenate((encode_state(state), action_onehot))

    def _opponent_training_samples(self, batch):
        """Extract per-opponent action labels from real joint transitions."""

        inputs = []
        targets = []
        delta_to_action = {
            delta: index
            for index, delta in enumerate(OPPONENT_ACTION_DELTAS[:4])
        }
        for experience in batch:
            if experience.next_world_state is None:
                continue
            current = world_state_to_game_state(experience.world_state)
            following = world_state_to_game_state(
                experience.next_world_state
            )
            remaining = {other[3] for other in following["others"]}
            current_bombs = {position for position, _timer in current["bombs"]}
            next_bombs = {position for position, _timer in following["bombs"]}

            # Unmoved opponents are matched first, then adjacent destinations.
            assignments = {}
            for opponent in current["others"]:
                position = opponent[3]
                if position in remaining:
                    assignments[position] = position
                    remaining.remove(position)
            for opponent in current["others"]:
                position = opponent[3]
                if position in assignments:
                    continue
                adjacent = sorted(
                    candidate
                    for candidate in remaining
                    if abs(candidate[0] - position[0])
                    + abs(candidate[1] - position[1])
                    == 1
                )
                if adjacent:
                    assignments[position] = adjacent[0]
                    remaining.remove(adjacent[0])

            for opponent in current["others"]:
                position = opponent[3]
                destination = assignments.get(position)
                if destination is None:
                    label = OPPONENT_REMOVED_INDEX
                elif destination == position:
                    placed_bomb = (
                        bool(opponent[2])
                        and position not in current_bombs
                        and position in next_bombs
                    )
                    label = 5 if placed_bomb else 4
                else:
                    delta = (
                        destination[0] - position[0],
                        destination[1] - position[1],
                    )
                    label = delta_to_action.get(delta, 4)
                inputs.append(
                    self._opponent_view_input(
                        current,
                        opponent,
                        experience.action_index,
                    )
                )
                targets.append(label)
        return inputs, targets

    def _train_opponent_model(self, batch):
        self.ensure_opponent_model_state()
        inputs, targets = self._opponent_training_samples(batch)
        if not inputs:
            return None
        targets = np.asarray(targets, dtype=np.int8)
        # Bomb placement and removal are rarer but tactically more important
        # than another ordinary movement sample.
        weights = np.ones(len(targets), dtype=np.float32)
        weights[targets == 5] = 2.0
        weights[targets == OPPONENT_REMOVED_INDEX] = 3.0
        self.opponent_model.partial_fit(
            np.stack(inputs),
            targets,
            classes=np.arange(len(OPPONENT_ACTIONS), dtype=np.int8),
            sample_weight=weights,
        )
        self.opponent_training_steps += 1
        self.opponent_last_loss = float(self.opponent_model.loss_)
        return self.opponent_last_loss

    def _correct_predicted_opponents(
        self,
        current_world_state,
        action_index,
        predicted_world_state,
    ):
        """Replace the weak occupancy reconstruction with factored actions."""

        self.ensure_opponent_model_state()
        if not self.is_opponent_model_ready:
            return predicted_world_state
        current = world_state_to_game_state(current_world_state)
        predicted = world_state_to_game_state(predicted_world_state)
        occupied = {predicted["self"][3]}
        corrected = []
        bomb_positions = {position for position, _timer in predicted["bombs"]}
        opponents = list(current["others"])
        encoded_opponents = [
            self._opponent_view_input(current, opponent, action_index)
            for opponent in opponents
        ]
        labels = (
            self.opponent_model.predict(np.stack(encoded_opponents))
            if encoded_opponents
            else []
        )
        for number, (opponent, predicted_label) in enumerate(
            zip(opponents, labels)
        ):
            label = int(predicted_label)
            if label == OPPONENT_REMOVED_INDEX:
                continue
            dx, dy = OPPONENT_ACTION_DELTAS[min(label, 5)]
            position = opponent[3]
            destination = (position[0] + dx, position[1] + dy)
            mechanically_valid = (
                predicted["field"][destination] == 0
                and destination not in occupied
                and (
                    destination == position
                    or destination not in bomb_positions
                )
            )
            if not mechanically_valid:
                destination = position
            if destination in occupied:
                continue
            occupied.add(destination)
            bombs_left = bool(opponent[2]) and label != 5
            corrected.append(
                (
                    f"predicted_opponent_{number}",
                    0,
                    bombs_left,
                    destination,
                )
            )
        predicted["others"] = corrected
        return game_state_to_world_state(predicted)

    def _train_bomb_head(
        self,
        model,
        inputs,
        targets,
        positive_weight,
        negative_weight=1.0,
    ):
        targets = np.asarray(targets, dtype=np.int8)
        weights = np.where(
            targets == 1,
            positive_weight,
            negative_weight,
        )
        model.partial_fit(
            inputs,
            targets,
            classes=np.asarray((0, 1), dtype=np.int8),
            sample_weight=weights,
        )
        return float(model.loss_)

    def _train_bomb_outcomes(self):
        self.ensure_bomb_outcome_state()
        if not self.bomb_outcome_replay:
            return None
        sample_size = min(self.batch_size, len(self.bomb_outcome_replay))
        kill_count = sample_size // 8 if self.bomb_kill_replay else 0
        failure_count = sample_size // 8 if self.bomb_failure_replay else 0
        ordinary_count = sample_size - kill_count - failure_count
        batch = self.rng.choices(
            self.bomb_outcome_replay,
            k=ordinary_count,
        )
        if kill_count:
            batch.extend(
                self.rng.choices(self.bomb_kill_replay, k=kill_count)
            )
        if failure_count:
            batch.extend(
                self.rng.choices(
                    self.bomb_failure_replay,
                    k=failure_count,
                )
            )
        inputs = np.stack([encode_state(item.state) for item in batch])
        losses = {
            "survival": self._train_bomb_head(
                self.bomb_survival_model,
                inputs,
                [item.survived for item in batch],
                positive_weight=1.0,
                # Rare failures are already forced into one eighth of every
                # batch; a moderate residual weight avoids overconfidence.
                negative_weight=2.0,
            ),
            "crate": self._train_bomb_head(
                self.bomb_crate_model,
                inputs,
                [item.destroyed_crate for item in batch],
                positive_weight=2.0,
            ),
            "kill": self._train_bomb_head(
                self.bomb_kill_model,
                inputs,
                [item.killed_opponent for item in batch],
                positive_weight=2.0,
            ),
        }
        threatened = [item for item in batch if any(item.state[35:39])]
        if threatened:
            threatened_inputs = np.stack(
                [encode_state(item.state) for item in threatened]
            )
            losses["escape"] = self._train_bomb_head(
                self.bomb_escape_model,
                threatened_inputs,
                [item.opponent_escaped for item in threatened],
                positive_weight=2.0,
            )
        else:
            losses["escape"] = None
        return losses

    def train_step(self, train_dynamics=True):
        if len(self.replay) < self.min_samples:
            return None

        sample_size = min(self.batch_size, len(self.replay))
        batch = self._balanced_batch(sample_size)
        agent_inputs = np.stack(
            [
                self._encode_agent_input(
                    item.state,
                    item.action_index,
                )
                for item in batch
            ]
        )
        agent_targets = np.stack(
            [self._encode_agent_target(item) for item in batch]
        )
        self.agent_model.partial_fit(
            agent_inputs,
            agent_targets,
        )
        # Termination probabilities must remain calibrated to the real event
        # frequency. Training this head on the deliberately balanced batch
        # would make terminal states appear far more common than they are.
        done_batch = [
            self.replay[self.rng.randrange(len(self.replay))]
            for _ in range(sample_size)
        ]
        done_inputs = np.stack(
            [
                self._encode_agent_input(
                    item.state,
                    item.action_index,
                )
                for item in done_batch
            ]
        )
        done_targets = np.asarray(
            [int(item.done) for item in done_batch],
            dtype=np.int8,
        )
        done_weights = np.where(done_targets == 1, 8.0, 1.0)
        self.done_model.partial_fit(
            done_inputs,
            done_targets,
            classes=np.asarray((0, 1), dtype=np.int8),
            sample_weight=done_weights,
        )
        death_loss = self._train_risk_head(
            self.death_model,
            "death_within_horizon",
            self.death_risk_replay,
            batch,
        )
        suicide_loss = self._train_risk_head(
            self.suicide_model,
            "suicide_within_horizon",
            self.suicide_risk_replay,
            batch,
        )
        opponent_loss = None
        if self.total_observations % OPPONENT_TRAIN_EVERY == 0:
            opponent_loss = self._train_opponent_model(batch)
        bomb_outcome_loss = None
        if len(self.bomb_outcome_replay) > self.bomb_outcomes_trained:
            # A bomb outcome changes only once per explosion. A few focused
            # updates per new label are both faster and less correlated than
            # retraining four classifiers after every movement step.
            for _ in range(4):
                bomb_outcome_loss = self._train_bomb_outcomes()
            self.bomb_outcomes_trained = len(self.bomb_outcome_replay)

        if train_dynamics:
            dynamics_inputs = np.stack(
                [
                    self._encode_input(
                        item.world_state,
                        item.state,
                        item.action_index,
                    )
                    for item in batch
                ]
            )
            dynamics_targets = np.stack(
                [self._encode_dynamics_target(item) for item in batch]
            )
            self.dynamics_model.partial_fit(
                dynamics_inputs,
                dynamics_targets,
            )
        self.training_steps += 1
        self.last_loss = {
            "dynamics": (
                float(self.dynamics_model.loss_)
                if hasattr(self.dynamics_model, "loss_")
                else None
            ),
            "agent": float(self.agent_model.loss_),
            "done": float(self.done_model.loss_),
            "death": death_loss,
            "suicide": suicide_loss,
            "opponent": opponent_loss,
            "bomb_outcome": bomb_outcome_loss,
        }
        return self.last_loss

    @staticmethod
    def _positive_probability(model, encoded_state):
        if not hasattr(model, "classes_"):
            return 0.0
        probabilities = model.predict_proba(encoded_state.reshape(1, -1))[0]
        positive_index = int(np.where(model.classes_ == 1)[0][0])
        return float(np.clip(probabilities[positive_index], 0.0, 1.0))

    def predict_bomb_outcome(self, state):
        """Predict delayed consequences of accepting BOMB in this state."""

        self.ensure_bomb_outcome_state()
        encoded = encode_state(state)
        threatened_opponent = any(state[35:39])
        return BombOutcomePrediction(
            survived_probability=self._positive_probability(
                self.bomb_survival_model,
                encoded,
            ),
            crate_probability=self._positive_probability(
                self.bomb_crate_model,
                encoded,
            ),
            kill_probability=self._positive_probability(
                self.bomb_kill_model,
                encoded,
            ),
            escape_probability=(
                self._positive_probability(
                    self.bomb_escape_model,
                    encoded,
                )
                if threatened_opponent
                else 0.0
            ),
        )

    def predict_death_probability(self, state, action_index):
        """Estimate all-cause death risk from compact opponent-aware state."""

        if not self.is_death_model_ready:
            return 0.0
        encoded_input = self._encode_agent_input(state, action_index)
        return float(
            self.death_model.predict_proba(
                encoded_input.reshape(1, -1)
            )[0, 1]
        )

    def predict_suicide_probability(self, state, action_index):
        """Estimate suicide risk without running the expensive board head."""

        if not self.is_suicide_model_ready:
            return 0.0
        encoded_input = self._encode_agent_input(state, action_index)
        return float(
            self.suicide_model.predict_proba(
                encoded_input.reshape(1, -1)
            )[0, 1]
        )

    def predict(self, world_state, state, action_index):
        """Generate a complete next state from a possibly imagined state."""

        if not self.is_ready:
            raise RuntimeError("The learned world model is not ready yet.")

        encoded_input = self._encode_input(world_state, state, action_index)
        encoded_agent_input = self._encode_agent_input(state, action_index)
        dynamics_output = self.dynamics_model.predict(
            encoded_input.reshape(1, -1)
        )[0]
        agent_output = self.agent_model.predict(
            encoded_agent_input.reshape(1, -1)
        )[0]
        state_size = len(world_state.vector)
        current_world = np.asarray(world_state.vector, dtype=np.float32)
        predicted_delta = (
            dynamics_output[:state_size]
            / world_target_weights(world_state.shape)
        )
        raw_next_world = current_world + predicted_delta
        next_world_state = project_world_state(
            WorldState(
                shape=world_state.shape,
                round_number=world_state.round_number,
                vector=tuple(float(value) for value in raw_next_world),
            )
        )
        next_world_state = self._correct_predicted_opponents(
            world_state,
            action_index,
            next_world_state,
        )

        next_state = decode_state(agent_output[:N_STATE_FEATURES])
        reward = float(
            np.clip(
                agent_output[N_STATE_FEATURES] / AGENT_REWARD_WEIGHT,
                -1.0,
                1.0,
            )
            * REWARD_SCALE
        )
        done_probability = float(
            self.done_model.predict_proba(
                encoded_agent_input.reshape(1, -1)
            )[0, 1]
        )
        suicide_probability = self.predict_suicide_probability(
            state,
            action_index,
        )
        death_probability = self.predict_death_probability(
            state,
            action_index,
        )
        legal_scores = agent_output[N_STATE_FEATURES + 1:]
        next_valid_actions = tuple(
            index
            for index, score in enumerate(legal_scores)
            if score >= 0.0
        )
        if 4 not in next_valid_actions:
            next_valid_actions += (4,)

        return Prediction(
            reward=reward,
            next_world_state=next_world_state,
            next_state=next_state,
            done_probability=done_probability,
            next_valid_actions=next_valid_actions,
            death_probability=death_probability,
            suicide_probability=suicide_probability,
        )
